const BrandList = [
    {
      id: '1',
      name: "McDonald's",
      image: "https://cdn.worldvectorlogo.com/logos/mcdonalds-1.svg",
      investment: "$1,000,000 - $2,500,000",
      category: "Food",
      rating: 4.8,
      location: "Worldwide",
      roi: "10-15%",
      establishmentTime: "12-18 months",
    },
    {
      id: '2',
      name: "Subway",
      image: "https://cdn.worldvectorlogo.com/logos/subway-3.svg",
      investment: "$100,000 - $500,000",
      category: "Food",
      rating: 4.5,
      location: "Worldwide",
      roi: "15-20%",
      establishmentTime: "6-12 months",
    },
    {
      id: '3',
      name: "Ixina",
      image: "https://www.fbd-group.com/fileadmin/sites/multiple/user_upload/phase_02/fbd_groupv1.5/pages/enseignes/ixina/enseigne.png",
      investment: "$200,000 - $800,000",
      category: "Retail",
      rating: 4.2,
      location: "Europe",
      roi: "12-18%",
      establishmentTime: "8-14 months",
    },
    {
      id: '4',
      name: "Puerta Real",
      image: "https://www.franquicia.net/wp-content/uploads/2022/04/puertareal-logo-300.jpg",
      investment: "$150,000 - $600,000",
      category: "Hospitality",
      rating: 4.0,
      location: "Spain",
      roi: "10-15%",
      establishmentTime: "6-12 months",
    },
    {
      id: '5',
      name: "Grupo Reprepol",
      image: "https://quefranquicia.com/sitepanel/wp-content/uploads/2021/11/logo-GRUPO-REPREPOL.jpg",
      investment: "$300,000 - $1,000,000",
      category: "Services",
      rating: 4.3,
      location: "Latin America",
      roi: "15-22%",
      establishmentTime: "9-15 months",
    },
    {
      id: '6',
      name: "Wayalia",
      image: "https://www.infofranquicias.com/media/mediauploads/logo/Wayalia-logo-w200.jpg",
      investment: "$50,000 - $200,000",
      category: "Health",
      rating: 4.1,
      location: "Europe",
      roi: "18-25%",
      establishmentTime: "3-6 months",
    },
    {
      id: '7',
      name: "Alfa Inmobiliaria",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSX4DUZTJ9hV3vOiP_t0kkSGYf-UetM5x-ROw&s",
      investment: "$100,000 - $400,000",
      category: "Real Estate",
      rating: 4.4,
      location: "Spain, Mexico",
      roi: "20-30%",
      establishmentTime: "4-8 months",
    },
    {
      id: '8',
      name: "Tea One",
      image: "https://www.generaldefranquicias.com/wp-content/uploads/2024/02/Franquicia-Teaone-3.png",
      investment: "$80,000 - $300,000",
      category: "Food & Beverage",
      rating: 4.2,
      location: "Asia, Europe",
      roi: "15-25%",
      establishmentTime: "5-10 months",
    },
  ];
  
  export default BrandList;
  